### ISSUE TITLE
qwt 6.1.6 is ready

### ISSUE THREAD

**Issue by kunlina** [opencor/qwt#2]
https://sourceforge.net/projects/qwt/files/qwt/6.1.6/

**Comment by agarny** [comment]
Thanks @kunlina, I hadn't realised that. Then again, the [Qwt page](https://qwt.sourceforge.io/) still mentions 6.1.5. Otherwise, note that the only reason [opencor](https://github.com/opencor)/[qwt](https://github.com/opencor/qwt) exists is to make things easier for our [OpenCOR](https://github.com/opencor/opencor) project (where we [build Qwt as part of CMake setup](https://github.com/opencor/opencor/blob/master/src/plugins/thirdParty/Qwt/CMakeLists.txt)). This being all said, [I have created an issue to update "our" copy of Qwt](https://github.com/opencor/opencor/issues/2483).
